"use strict";
let favoriteMovie = "The Lord of the Rings";
let FirstName = "Fazan";
let LastName = "Arshad";
let age = 34;
console.log(`Hello, my name is ${FirstName} and I am ${age} year old.`);
const Happy = true;
console.log(`Full Name: ${FirstName} ${LastName}`);
let userAge = 34;
let productName = "Headphones";
let price = 99.99;
console.log(`${productName} - Price: $${(99.99).toFixed(2)}`);
let numPets = 2;
let isBirthday = false;
console.log(`User Information: First Name: ${FirstName} Last Name: ${LastName} Age: ${34}`);
const birthYear = 1989;
let city = "multan";
let country = "pakistan";
console.log(`${city}, ${country}.`);
let temperature = 29;
console.log(`Today's Temperature: ${29}°C`);
